
events {
}

http {

    upstream servidores {
    ip_hash;
    server servidor1:8000;
    server servidor2:8000;
    server servidor3:8000;
    server servidor4:8000;
    server servidor5:8000;
    server servidor6:8000;
}

    server {
        listen 80;

        location / {
            proxy_pass http://servidores;
        }
    }
}
